language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - PYTHONPATH=./
  - DJANGO_SETTINGS_MODULE='moto.moe.settings'
services:
  - redis-server
install:
  - pip install --upgrade pip
  - sudo apt-get install python3-lxml
  - pip install git+https://github.com/bung87/moto-moe 
  - pip install -r https://raw.githubusercontent.com/bung87/moto-moe/master/dependency_links.txt

before_script:
  - mysql -e 'create database moto;'
script:
  - django-admin syncdb
  - django-admin migrate
  - django-admin test moto.moe