language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO_SETTINGS_MODULE='moto.moe.settings'
services:
  - redis-server
install:
  - sudo apt-get install python3-lxml
  - pip install git+https://github.com/bung87/moto-moe  --process-dependency-links --allow-all-external  moto-moe --trusted-host github.com
  - django-admin syncdb –migrate –noinput
before_script:
  - mysql -e 'create database moto;
scripts:
  - django-admin test moe